INSERT INTO DOMAIN_TABLE (DOMAIN_NAME) VALUES ('google.com');
INSERT INTO DOMAIN_TABLE (DOMAIN_NAME) VALUES ('yahoo.com');
INSERT INTO DOMAIN_TABLE (DOMAIN_NAME) VALUES ('evil.com');
INSERT INTO DOMAIN_TABLE (DOMAIN_NAME) VALUES ('me.com');
INSERT INTO DOMAIN_TABLE (DOMAIN_NAME) VALUES ('sdfsd.com');
